##
# Update the APT package cache and install packages as a root user
##
- name: Install required packages
  apt:
    state: present
    name:
    - python3-setuptools
    - python3-wheel
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - python3-psycopg2 # Required for manage postgres
    - acl # Access control list, required from grant some permissions
  become: yes

- name: Create app directory
  file:
    path: '{{ app_dir }}'
    state: directory

- name: Create venv directory
  file:
    path: '{{ venv_root }}'
    state: directory

- name: Create the enviroment file for django
  template:
    src: .env.prod
    dest: '{{ env_file }}'
  become: yes

